---

- hosts: all
  become: true
  
  tasks:
   
    - name: copying the html file to servers
      tags: copy,file
      copy:
        src: simple-site.html
        dest: /var/www/html/index.html
        mode: '0644'

